apiVersion: v1
kind: ServiceAccount
metadata:
  name: secrets-injector
  labels:
    app: secrets-injector
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: secrets-injector
  labels:
    app: secrets-injector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: secrets-injector
subjects:
  - kind: ServiceAccount
    name: secrets-injector
    namespace: test-injector
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: secrets-injector
  labels:
    app: secrets-injector
rules:
  - apiGroups: ["admissionregistration.k8s.io"]
    resources: ["mutatingwebhookconfigurations"]
    verbs: ["create", "get", "delete", "list", "patch", "update", "watch"]
  - apiGroups: [""] # "" indicates the core API group
    resources: ["secrets"]
    verbs: ["get"]
